# Generated by Django 2.2 on 2020-02-21 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 2, 21)),
        ),
    ]
