# Generated by Django 2.2 on 2020-02-21 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20200221_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reg_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
