# Generated by Django 2.2 on 2020-02-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20200221_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pdpa_checked',
            field=models.BooleanField(default=False),
        ),
    ]
