# Generated by Django 2.2 on 2020-03-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_userprofile_is_pdpa_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_photo',
            field=models.FileField(default='', upload_to='photos'),
        ),
    ]
