# Generated by Django 2.2 on 2020-03-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_userprofile_mobile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_photo',
            field=models.FileField(default='', upload_to='photos/'),
        ),
    ]
