# Generated by Django 2.2 on 2020-03-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20200306_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_photo',
            field=models.FileField(default='', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(default='', null=True, upload_to='photos/'),
        ),
    ]
