# Generated by Django 2.2 on 2020-03-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_auto_20200306_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_photo',
        ),
    ]
