# Generated by Django 2.2 on 2020-03-09 05:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_remove_userprofile_mobile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[640, 480], upload_to='photos/'),
        ),
    ]
