# Generated by Django 2.2 on 2020-03-09 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_auto_20200309_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_access_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
