# Generated by Django 2.2 on 2020-03-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_userprofile_last_access_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nric_number',
            field=models.CharField(default='', error_messages={'unique': 'You provided a registered NRIC/FIN'}, max_length=255, unique=True),
        ),
    ]
