# Generated by Django 2.2 on 2020-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_auto_20200310_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nric_number',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
