# Generated by Django 2.2 on 2020-07-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_auto_20200310_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
